FROM ghcr.io/chenxiex/devcontainer-templates/devcontainer-devops-alpine3.23:latest

# [Optional] Uncomment this section to install additional OS packages.
# RUN apk add --no-cache <your-package-list-here>
